Fix exception caused by #1096
```cs
MediaBrowser.Common.Extensions.ResourceNotFoundException: Configuration
with key subtitles not found.
   at
   Emby.Server.Implementations.AppBase.BaseConfigurationManager.<>c__DisplayClass42_0.<GetConfiguration>b__0(String
   k) in
   /home/pi/dev/jellyfin/Emby.Server.Implementations/AppBase/BaseConfigurationManager.cs:line
   247
      at
      System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey
      key, Func`2 valueFactory)
         at
	 Emby.Server.Implementations.AppBase.BaseConfigurationManager.GetConfiguration(String
	 key) in
	 /home/pi/dev/jellyfin/Emby.Server.Implementations/AppBase/BaseConfigurationManager.cs:line
	 238
	    at
	    MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.AddExternalSubtitles(Video
	    video, List`1 currentStreams, MetadataRefreshOptions
	    options, CancellationToken cancellationToken) in
	    /home/pi/dev/jellyfin/MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs:line
	    486
	       at
	       MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.Fetch(Video
	       video, CancellationToken cancellationToken, MediaInfo
	       mediaInfo, BlurayDiscInfo blurayInfo,
	       MetadataRefreshOptions options) in
	       /home/pi/dev/jellyfin/MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs:line
	       204
	          at
		  MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T
		  item, MetadataRefreshOptions options,
		  CancellationToken cancellationToken) in
		  /home/pi/dev/jellyfin/MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs:line
		  119
		     at
		     MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1
		     provider, TItemType item, String logName,
		     MetadataRefreshOptions options, RefreshResult
		     refreshResult, CancellationToken cancellationToken)
		     in
		     /home/pi/dev/jellyfin/MediaBrowser.Providers/Manager/MetadataService.cs:line
		     806

```