Delay initialization of singleton services during migration CoreInitialisation stage
Change:
Delay initialization of singleton services during migration CoreInitialisation stage

Fixes:
Jellyfin code migrations that run during EF Core migrations generate:

[07:35:34] [ERR] [7] InternalCodeMigration: Migration 20250814000002_RemoveDuplicatePeopleStage2 failed
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager..ctor(IMemoryCache memoryCache) in /src/MediaBrowser.Providers/Plugins/Tmdb/TmdbClientManager.cs:line 40

due to TmdbClientManager being initialized too early.