Refresh user record before updating/deleting to avoid DbUpdateConcurrencyException
Change:
Refresh user record before updating/deleting to avoid DbUpdateConcurrencyException

Issue:
[16:35:17] [ERR] [91] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL DELETE /Users/3f18f29e944c43f0b75981be1190b046.
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See https://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.