Fix race conditions in AudioDb and Omdb provider file system caches
With unfortunate timing multiple async tasks might try to write the
same file concurrently, resulting in the IOException below.

```
[ERR] Error in "The Open Movie Database"
System.IO.IOException: The process cannot access the file '/var/cache/jellyfin/omdb/tt4564123.json' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Init
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open
   at System.IO.Strategies.OSFileStreamStrategy..ctor
   at System.IO.FileStream..ctor
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.EnsureItemInfo
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.GetRootObject
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.Fetch[T]
   at MediaBrowser.Providers.Plugins.Omdb.OmdbItemProvider.GetResult[T]
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders
```