Fix SQLite Error 5: 'database is locked' and other db errors.
The main problem that is happening is that jelly fin is breaking the sqlite Multi-thread mode rules and EF is not helping in any way.
https://www.sqlite.org/threadsafe.html
EF uses the Multi-thread mode of sqlite.

These basically break down to:
* Reads can be multi-threaded
* Only one write operation can happen at any one time (this includes overlapping reads, i.e. a read during a write operation/transaction can cause the 'database is locked')
* Only one transaction scope at one time (no overlapping writes or transactions)

In sqlite you can set a retry timeout but that doesn't help if you transactions.

My fix is to use i reader writer lock primitive (multiple readers but only one writer) at i coarse-grained lock level.
This means it's not automatically added to JellyFin but has to be added to db usage areas manually and maintained.
I have done this for the current db usage and tried to limit the db lock scope as much as makes sense.

The implementation also supports recursive locking, including upgrading/downgrading locks.

- Added `DotNext.Threading` package reference for AsyncReaderWriterLock.
- Introduced `Jellyfin.Database.Implementations.Locking` for database locking.
- Updated classes to include `IEntityFrameworkDatabaseLockingBehavior` for managing locks.
- Refactored methods in `CleanDatabaseScheduledTask`, `UserDataManager`, and others to use reader/writer locks.
- Implemented new locking strategies with `ConcurrentDatabaseLockingBehavior` and `SerializedDatabaseLockingBehavior`.
- Improved error handling and logging for better insights during database operations.

Also fixed
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
...
   at Jellyfin.Database.Implementations.JellyfinDbContext.SaveChanges(Boolean acceptAllChangesOnSuccess) in D:\depot\github\jellyfin\src\Jellyfin.Database\Jellyfin.Database.Implementations\JellyfinDbContext.cs:line 286
   at Jellyfin.Server.Implementations.Item.PeopleRepository.UpdatePeople(Guid itemId, IReadOnlyList`1 people) in D:\depot\github\jellyfin\Jellyfin.Server.Implementations\Item\PeopleRepository.cs:line 106
   at Emby.Server.Implementations.Library.LibraryManager.UpdatePeopleAsync(BaseItem item, IReadOnlyList`1 people, CancellationToken cancellationToken) in D:\depot\github\jellyfin\Emby.Server.Implementations\Library\LibraryManager.cs:line 2864
   at Emby.Server.Implementations.Library.LibraryManager.UpdatePeople(BaseItem item, List`1 people) in D:\depot\github\jellyfin\Emby.Server.Implementations\Library\LibraryManager.cs:line 2850

With the multi-threaded nature of JellyFin, multiple overlapping calls to PeopleRepository.UpdatePeople can cause this problem.
The write locking scope fixes this sort of problem, I also added a transaction boundary if JellyFin is gonig to support other db types where locking behavior can be turned off.